### ISSUE TITLE
Dash in region name

### ISSUE THREAD

**Issue by ivs** [louis-e/arnis#14]
Hi! Dash in state name does not work for Russian regions:
https://github.com/louis-e/arnis/blob/main/src/getData.py#L27

I've tested it here: https://overpass-turbo.eu/
This one works:
```
[out:json];
area[name="Иркутск"]->.city;
area[name="Иркутская область"]->.state;
area[name="Россия"]->.country;
way(area.country)(area.state)(area.city)[!power][!place][!ferry];
(._;>;);
out;
```

And this one(as replace in code do) doesn't
`area[name="Иркутская область"]->.state;`

Link to the city: https://www.openstreetmap.org/relation/1430614

Not sure is it Russia states problem or a global one, maybe Denmark regions have the same issue: https://github.com/louis-e/arnis/issues/12

**Comment by louis-e** [comment]
Hi there, thanks for reporting this! Yeah, I've seen that this is the case for a lot of countries. I'm sometimes confused with the OSM naming standards, seems like the dash is just required in some cases. Will adjust this in the code and in the Readme. Thanks a lot!
