### ISSUE TITLE
not really sure how to start up

### ISSUE THREAD

**Issue by PopsEj** [louis-e/arnis#20]
idk how to use this is there a way that you can help cause I really wanna put New York in minecraft

**Comment by louis-e** [comment]
Hi there! To generate New York, download the source code of this project and run it using `python3 arnis.py --city "City of New York" --state "New York" --country "United States" --path "C:/Users/username/AppData/Roaming/.minecraft/saves/worldname"` [(see usage)](https://github.com/louis-e/arnis#keyboard-usage).

Please keep in mind that New York is quite a large city and might take some time to generate, depending on your hardware. It could even be that the algorithm won't be capable of calculating such a big city. I'm quite busy currently, but I might produce a video guide for Arnis soon.
I'm going to close this issue for now, feel free to open it again if you need further assistance. Thanks!
