### ISSUE TITLE
how do I do overpass

### ISSUE THREAD

**Issue by PopsEj** [louis-e/arnis#21]
when I try to go to https://overpass-api.de/api/interpreter it doesn't work. I tried overpass turbo. it selects random servers. I downloaded a file from overpass the geo file. that didn't work

**Comment by louis-e** [comment]
Hi there, Overpass Turbo is not in the scope for this project. If you want to test queries using an user interface, try https://overpass-turbo.eu/s/1Cjw. If you could provide me your exact input details, I can help you out with finding the correct parameters. Thanks a lot!

Official Overpass Turbo Repository: https://github.com/tyrasd/overpass-turbo

**Comment by PopsEj** [comment]
> Hi there, Overpass Turbo is not in the scope for this project. If you want to test queries using an user interface, try https://overpass-turbo.eu/s/1Cjw. If you could provide me your exact input details, I can help you out with finding the correct parameters. Thanks a lot!
> 
> Official Overpass Turbo Repository: https://github.com/tyrasd/overpass-turbo

{
  "version": 0.6,
  "generator": "Overpass API 0.7.61.5 4133829e",
  "osm3s": {
    "timestamp_osm_base": "2023-10-23T17:34:00Z",
    "timestamp_areas_base": "2023-10-23T12:08:15Z",
    "copyright": "The data included in this document is from www.openstreetmap.org. The data is made available under ODbL."
  },
  "elements": [

{
  "type": "area",
  "id": 3600061320,
  "tags": {
    "ISO3166-2": "US-NY",
    "admin_level": "4",
    "alt_name": "New York State",
    "border_type": "state",
    "boundary": "administrative",
    "name": "New York",
    "name:ar": "نيويورك",
    "name:az": "Nyu-York",
    "name:bg": "Ню Йорк",
    "name:br": "New York",
    "name:ca": "Nova York",
    "name:chr": "ᏄᏲᎩ",
    "name:cv": "Çĕнĕ Йорк",
    "name:cy": "Efrog Newydd",
    "name:el": "Νέα Υόρκη",
    "name:en": "New York",
    "name:eo": "Nov-Jorkio",
    "name:es": "Nueva York",
    "name:ga": "Nua-Eabhrac",
    "name:gd": "Eabhraig Nuadh",
    "name:gv": "York Noa",
    "name:hak": "New York",
    "name:haw": "Nuioka",
    "name:he": "ניו יורק",
    "name:ik": "Tchiaq York",
    "name:ja": "ニューヨーク州",
    "name:ka": "ნიუ-იორკი",
    "name:ko": "뉴욕",
    "name:la": "Novum Eboracum",
    "name:lv": "Ņujorka",
    "name:nah": "Yancuīc York",
    "name:nan": "New York",
    "name:nv": "Nííyóó Hahoodzo",
    "name:pl": "Nowy Jork",
    "name:pt": "Nova Iorque",
    "name:ru": "Нью-Йорк",
    "name:sr": "Њујорк",
    "name:ta": "நியூ யோர்க்",
    "name:uk": "Нью-Йорк",
    "name:yi": "ניו יארק",
    "name:zh": "纽约州 / 紐約州",
    "name:zh-Hans": "纽约州",
    "name:zh-Hant": "紐約州",
    "old_name:vi": "Nữu Ước",
    "population": "20201249",
    "population:date": "2020",
    "ref": "NY",
    "ref:USCG": "NY",
    "ref:USPS": "NY",
    "ref:fips": "36",
    "short_name": "N.Y.",
    "source:name:br": "ofis publik ar brezhoneg",
    "source:short_name": "Associated Press",
    "type": "boundary",
    "wikidata": "Q1384",
    "wikipedia": "en:New York (state)"
  }
},
{
  "type": "area",
  "id": 3600148838,
  "tags": {
    "ISO3166-1": "US",
    "ISO3166-1:alpha2": "US",
    "ISO3166-1:alpha3": "USA",
    "ISO3166-1:numeric": "840",
    "admin_level": "2",
    "alt_name:be": "Злучаныя Штаты;Штаты",
    "alt_name:en": "America",
    "alt_name:es": "Estados Unidos;EUA",
    "alt_name:fr": "États-Unis",
    "alt_name:ko": "아메리카",
    "alt_name:vi": "Hoa Kì;Mĩ;Hợp chúng quốc Hoa Kì",
    "alt_short_name:en": "US",
    "alt_short_name:pl": "St. Zj.",
    "border_type": "national",
    "boundary": "administrative",
    "default_language": "en",
    "flag": "https://upload.wikimedia.org/wikipedia/commons/a/a4/Flag_of_the_United_States.svg",
    "int_name": "United States of America",
    "int_name:ko": "아메리카합중국",
    "name": "United States",
    "name:ab": "Америка Еиду Аштатқәа",
    "name:ace": "Amirika Carékat",
    "name:af": "Verenigde State van Amerika",
    "name:als": "Vereinigte Schtaate vo Amerika",
    "name:am": "የተባበሩት የአሜሪካ ግዛቶች",
    "name:an": "Estatos Unitos d'America",
    "name:anc": "Ἡνωμέναι Πολιτείαι τῆς Νεοικουμένης",
    "name:ang": "Geānlǣtan Rīcu American",
    "name:ar": "الولايات المتّحدة الأمريكيّة",
    "name:arc": "ܐܘܚܕܢܐ ܡܚܝܕܐ",
    "name:arz": "امريكا",
    "name:as": "মাৰ্কিন যুক্তৰাষ্ট্ৰ",
    "name:ast": "Estaos Xuníos d'América",
    "name:av": "Америкалъул Цолъарал Штатал",
    "name:ay": "Istadus Unidus",
    "name:az": "Amerika Birləşmiş Ştatları",
    "name:az-Arab": "آمریکا بیرلشمیش ایالتلری",
    "name:azb": "آمریکا بیرلشمیش ایالتلری",
    "name:ba": "Америка Ҡушма Штаттары",
    "name:bar": "Vaeinigtn Staatn vo Amerika",
    "name:bat-smg": "JAV",
    "name:bcl": "Estados Unidos",
    "name:be": "Злучаныя Штаты Амерыкі",
    "name:be-tarask": "Злучаныя Штаты Амэрыкі",
    "name:bg": "Съединени американски щати",
    "name:bi": "Yunaeted Stet blong Amerika",
    "name:bm": "Amerika ka Kelenyalen Jamanaw",
    "name:bn": "মার্কিন যুক্তরাষ্ট্র",
    "name:bo": "ཨ་མེ་རི་ཁ་རྒྱལ་ཕྲན་མཉམ་འབྲེལ་རྒྱལ་ཁབ།",
    "name:bpy": "তিলপারাষ্ট্র",
    "name:br": "Stadoù-Unanet Amerika",
    "name:bs": "Sjedinjene Američke Države",
    "name:bxr": "Американ Нэгэдэһэн Улас",
    "name:ca": "Estats Units d'Amèrica",
    "name:cbk-zam": "Estados Unidos de America",
    "name:cdo": "Mī-lé-giĕng Hăk-cé̤ṳng-guók",
    "name:ce": "Iамерка пачхьалк",
    "name:ceb": "Estados Unidos sa Amerika",
    "name:chr": "ᏌᏊᎢᏳᎾᎵᏍᏔᏅᏍᎦᏚᎩ ᎾᎿ ᎠᎺᏰᏟ",
    "name:chy": "United States",
    "name:ckb": "ویلایەتە یەکگرتووەکانی ئەمریکا",
    "name:co": "Stati Uniti d'America",
    "name:crh": "Amerika Qoşma Ştatları",
    "name:cs": "Spojené státy americké",
    "name:csb": "Zjednóné Kraje Americzi",
    "name:cu": "Амєрика́ньскꙑ Ѥдьнѥнꙑ́ Дрьжа́вꙑ",
    "name:cv": "Америкăри Пĕрлешӳллĕ Штатсем",
    "name:cy": "Unol Daleithiau America",
    "name:da": "Amerikas Forenede Stater",
    "name:de": "Vereinigte Staaten von Amerika",
    "name:din": "Amatnhom Pawut",
    "name:diq": "Dewletê Amerikayê Yewbiyayey",
    "name:dsb": "Zjadnośone staty Ameriki",
    "name:dv": "އެމެރިކާ",
    "name:dz": "ཡུ་ནའིཊེཊ་སི་ཊེས",
    "name:ee": "United States",
    "name:el": "Ηνωμένες Πολιτείες της Αμερικής",
    "name:eml": "Stat Unî",
    "name:en": "United States",
    "name:eo": "Usono",
    "name:es": "Estados Unidos de América",
    "name:et": "Ameerika Ühendriigid",
    "name:eu": "Ameriketako Estatu Batuak",
    "name:ext": "Estaus Uñíus d'América",
    "name:fa": "ایالات متحده آمریکا",
    "name:ff": "Dowlaaji Dentuɗi",
    "name:fi": "Amerikan yhdysvallat",
    "name:fo": "Sambandsríkið Amerika",
    "name:fr": "États-Unis d'Amérique",
    "name:frp": "Ètats-Unis d’Amèrica",
    "name:frr": "Feriind Stoote foon Ameerika",
    "name:fur": "Stâts Unîts di Americhe",
    "name:fy": "Feriene Steaten fan Amearika",
    "name:ga": "Stáit Aontaithe Mheiriceá",
    "name:gag": "Amerika Birleşik Devletläri",
    "name:gan": "美國",
    "name:gd": "Na Stàitean Aonaichte",
    "name:gl": "Estados Unidos de América",
    "name:glk": "امریکا",
    "name:gn": "Tetã peteĩ reko Amérikagua",
    "name:grc": "Ἡνωμέναι Πολιτεῖαι τῆς Ἀμερικῆς",
    "name:gu": "સંયુક્ત રાજ્ય અમેરિકા",
    "name:gv": "Steatyn Unnaneysit America",
    "name:ha": "kunkiyar taraiyar Amurika",
    "name:hak": "Mî-li-kiên Ha̍p-chung-koet",
    "name:haw": "ʻAmelika Hui Pū ʻia",
    "name:he": "ארצות הברית",
    "name:hi": "संयुक्त राज्य अमेरिका",
    "name:hif": "United States",
    "name:hr": "Sjedinjene Američke Države",
    "name:hsb": "Zjednoćene staty Ameriki",
    "name:ht": "Etazini",
    "name:hu": "Amerikai Egyesült Államok",
    "name:hy": "Ամերիկայի Միացյալ Նահանգներ",
    "name:ia": "Statos Unite de America",
    "name:id": "Amerika Serikat",
    "name:ie": "Unit States de America",
    "name:ig": "Njikota Obodo Amerika",
    "name:ik": "United States of America",
    "name:ilo": "stados Unidos iti Amerika",
    "name:io": "Unionita Stati di Amerika",
    "name:is": "Bandaríki Norður-Ameríku",
    "name:it": "Stati Uniti d'America",
    "name:iu": "ᐊᒥᐊᓕᑲ",
    "name:ja": "アメリカ合衆国",
    "name:jbo": ".iunaited.steits.",
    "name:jv": "Amérika Sarékat",
    "name:ka": "ამერიკის შეერთებული შტატები",
    "name:kaa": "Amerika Qurama Shtatları",
    "name:kab": "Iwunak Yedduklen",
    "name:kbd": "Америкэ Штат Зэгуэт",
    "name:ki": "United States",
    "name:kk": "Америка Құрама Штаттары",
    "name:kk-Arab": "امەرىيكا قۇراما شتاتتارى",
    "name:kl": "Naalagaaffeqatigiit",
    "name:km": "សហរដ្ឋអាមេរិក",
    "name:kn": "ಅಮೇರಿಕ ಸಂಯುಕ್ತ ಸಂಸ್ಥಾನ",
    "name:ko": "미국",
    "name:koi": "Америкаись Ӧтлаасьӧм Штаттэз",
    "name:krc": "Американы Бирлешген Штатлары",
    "name:ks": "ریاست ہائے متحدہ",
    "name:ksh": "Vereenichde Staate van Amerika",
    "name:ku": "Dewletên Yekbûyî yên Amerîkayê",
    "name:kv": "Америкаса Ӧтувтӧм Штатъяс",
    "name:kw": "Statys Unys Amerika",
    "name:ky": "Америка Кошмо Штаттары",
    "name:la": "Civitates Foederatae Americae",
    "name:lad": "Estatos Unitos d'Amerika",
    "name:lb": "Vereenegt Staate vun Amerika",
    "name:lbe": "Американал ЦачӀунхьу Штатру",
    "name:lez": "Америкадин Садхьанвай Штатар",
    "name:lg": "Amereka",
    "name:li": "Vereinegde State van Amerika",
    "name:lij": "Stati Unïi d'America",
    "name:lmo": "Stat Ünì d'America",
    "name:ln": "Lisangá lya Ameríka",
    "name:lo": "ສະຫະລັດອາເມລິກາ",
    "name:lt": "Jungtinės Amerikos Valstijos",
    "name:ltg": "Amerikys Saškierstuos Vaļsteibys",
    "name:lv": "Amerikas Savienotās Valstis",
    "name:lzh": "美利堅合眾國",
    "name:map-bms": "Amerika Serikat",
    "name:mdf": "Америконь Аймакнень Соткссна",
    "name:mg": "Etazonia",
    "name:mhr": "Америкысе Ушымо Штатвлак",
    "name:mi": "Amerika",
    "name:mia": "mihši-maalhsonki",
    "name:min": "Amerika Sarikat",
    "name:mk": "Соединети Американски Држави",
    "name:ml": "അമേരിക്കന് ഐക്യനാടുകള്",
    "name:mn": "Америкийн Нэгдсэн Улс",
    "name:mo": "Стателе Уните але Америчий",
    "name:mr": "अमेरिकेची संयुक्त संस्थाने",
    "name:mrj": "Америкын Ушымы Штатвлӓжӹ",
    "name:ms": "Amerika Syarikat",
    "name:mt": "Stati Uniti tal-Amerika",
    "name:mwl": "Stados Ounidos de la América",
    "name:my": "အမေရိကန်ပြည်ထောင်စု",
    "name:myv": "Американь Вейтьсэндявкс Штаттнэ",
    "name:mzn": "متحده ایالات آمریکا",
    "name:na": "Eben Merika",
    "name:nah": "Tlacetilīlli Tlahtohcāyōtl Ixachitlān",
    "name:nan": "America Ha̍p-chiòng-kok",
    "name:nap": "State Aunite d'Amereca",
    "name:nds": "Verenigten Staten vun Amerika",
    "name:nds-nl": "Verienigde Staoten van Amerika",
    "name:ne": "संयुक्त राज्य अमेरिका",
    "name:new": "संयुक्त राज्य अमेरिका",
    "name:nl": "Verenigde Staten",
    "name:nn": "USA",
    "name:no": "Amerikas forente stater",
    "name:nov": "Unionati States de Amerika",
    "name:nrm": "Êtats Unnis d'Améthique",
    "name:nso": "United States of America",
    "name:nv": "Wááshindoon Bikéyah Ałhidadiidzooígíí",
    "name:oc": "Estats Units d'America",
    "name:om": "USA",
    "name:or": "ଯୁକ୍ତରାଷ୍ଟ୍ର ଆମେରିକା",
    "name:os": "Америкæйы Иугонд Штаттæ",
    "name:pa": "ਸੰਯੁਕਤ ਰਾਜ ਅਮਰੀਕਾ",
    "name:pag": "Estados Unidos",
    "name:pam": "United States ning America",
    "name:pap": "Estadonan Uni di Merka",
    "name:pcd": "États-Unis Anmérikes",
    "name:pdc": "Vereenichde Schtaate vun Amerikaa",
    "name:pfl": "Verainischde Schdaade vun Ameriga",
    "name:pih": "Yunitid Staits",
    "name:pl": "Stany Zjednoczone",
    "name:pms": "Stat Unì d'América",
    "name:pnb": "امریکہ",
    "name:ps": "د امریکا متحده آیالاتونه",
    "name:pt": "Estados Unidos da América",
    "name:qu": "Hukllachasqa Amirika Suyukuna",
    "name:rm": "Stadis Unids da l'America",
    "name:rn": "Leta Zunze Ubumwe za Amerika",
    "name:ro": "Statele Unite ale Americii",
    "name:roa-tara": "Statère Aunìte d'Americhe",
    "name:ru": "Соединённые Штаты Америки",
    "name:rue": "Споєны Штаты Америцькы",
    "name:rw": "Leta Zunze Ubumwe z’Amerika",
    "name:sa": "संयुक्तानि राज्यानि",
    "name:sah": "Америка Холбоһуктаах Штаттара",
    "name:sc": "Istados Unidos de America",
    "name:scn": "Stati Uniti",
    "name:sco": "Unitit States o Americae",
    "name:sd": "آمريڪا",
    "name:se": "Amerihká ovttastuvvan stáhtat",
    "name:sg": "ÂKödörö-ôko tî Amerîka",
    "name:sh": "Sjedinjene Američke Države",
    "name:si": "අ'මෙරිකාවේ එක්සත් රාජ්යයන්",
    "name:sk": "Spojené štáty americké",
    "name:sl": "Združene države Amerike",
    "name:sm": "Iunaite Sitete o Amerika",
    "name:smn": "Amerik ovtâstumstaatah",
    "name:sms": "Ameriikk õhttõõvvâmvääʹld",
    "name:sn": "United States of America",
    "name:so": "Mareykanka",
    "name:sq": "Shtetet e Bashkuara të Amerikës",
    "name:sr": "Сједињене Америчке Државе",
    "name:sr-Latn": "Sjedinjene Američke Države",
    "name:srn": "Kondre Makandrameki",
    "name:ss": "IMelika",
    "name:stq": "Fereende Stoaten fon Amerikoa",
    "name:su": "Amérika Sarikat",
    "name:sv": "USA",
    "name:sw": "Muungano wa Madola ya Amerika",
    "name:syc": "ܐܘܚܕܢܐ ܡܚܝܕܐ",
    "name:szl": "Zjednoczōne Sztaty Ameryki",
    "name:ta": "ஐக்கிய அமெரிக்கா",
    "name:te": "అమెరికా సంయుక్త రాష్ట్రాలు",
    "name:tet": "Estadu Naklibur Sira Amérika Nian",
    "name:tg": "Иёлоти Муттаҳидаи Амрико",
    "name:th": "สหรัฐอเมริกา",
    "name:tk": "Amerikanyň Birleşen Ştatlary",
    "name:tl": "Estados Unidos",
    "name:tn": "USA",
    "name:to": "Puleʻanga Fakataha 'o 'Amelika",
    "name:tpi": "Yunaitet Stet bilong Amerika",
    "name:tr": "Amerika Birleşik Devletleri",
    "name:ts": "United States",
    "name:tt": "Америка Кушма Штатлары",
    "name:tw": "USA",
    "name:ty": "Fenua Marite",
    "name:tzl": "Estats Viensiçeschti d'America",
    "name:udm": "Америкалэн Огазеяськем Штатъёсыз",
    "name:ug": "ئامېرىكا قوشما شتاتلىرى",
    "name:uk": "Сполучені Штати Америки",
    "name:ur": "ریاست ہائے متحدہ",
    "name:uz": "Amerika Qoʻshma Shtatlari",
    "name:vec": "Stati Unìi de la Mèrica",
    "name:vep": "Amerikan Ühtenzoittud Valdkundad",
    "name:vi": "Hoa Kỳ",
    "name:vls": "Verênigde Stoaten van Amerika",
    "name:vo": "Lamerikän",
    "name:vro": "Ameeriga Ütisriigiq",
    "name:wa": "Estats Unis d' Amerike",
    "name:war": "Estados Unidos",
    "name:wo": "Diwaan-yu-Bennoo yu Aamerig",
    "name:wuu": "美国",
    "name:xal": "Америкин Ниицәтә Орн Нутгуд",
    "name:xh": "IYunayithedi Steyitsi",
    "name:xmf": "ამერიკაშ აკოართაფილი შტატეფი",
    "name:yi": "פאראייניקטע שטאטן פון אמעריקע",
    "name:yo": "Àwọn Ìpínlẹ̀ Aṣọ̀kan Amẹ́ríkà",
    "name:yue": "美利堅合眾國",
    "name:za": "Meijgoz",
    "name:zea": "Vereênigde Staeten",
    "name:zh": "美利坚合众国/美利堅合眾國",
    "name:zh-Hans": "美利坚合众国",
    "name:zh-Hant": "美利堅合眾國",
    "name:zu": "IMelika",
    "not:official_name:vi": "Hợp chủng quốc Hoa Kỳ;Hợp chúng quốc Hoa Kì;Hợp chủng quốc Hoa Kỳ;Hợp chủng quốc Hoa Kì",
    "official_name": "United States of America",
    "official_name:ar": "الوِلَايَات المُتَّحِدَة الأَمرِيكِيَّة",
    "official_name:arc": "ܐܬܪܘܬܐ ܡܚܝܕܐ ܕܐܡܪܝܟܐ",
    "official_name:cs": "Spojené státy americké",
    "official_name:de": "Vereinigte Staaten von Amerika",
    "official_name:din": "Pawuut Matiic ke Amerïka",
    "official_name:en": "United States of America",
    "official_name:eo": "Unuiĝintaj Ŝtatoj de Ameriko",
    "official_name:es": "Estados Unidos de América",
    "official_name:grc": "Ἡνωμέναι Πολιτεῖαι τῆς Ἀμερικῆς",
    "official_name:kk-Arab": "امەرىيكا قۇراما شتاتتارى",
    "official_name:ko": "미합중국",
    "official_name:ks": "ریاست ہائے متحدہ",
    "official_name:nl": "Verenigde Staten van Amerika",
    "official_name:pl": "Stany Zjednoczone Ameryki",
    "official_name:ps": "د امریکا متحده آیالاتونه",
    "official_name:sv": "Amerikas Förenta Stater",
    "official_name:syc": "ܐܬܪܘܬܐ ܡܚܝܕܐ ܕܐܡܪܝܟܐ",
    "official_name:ug": "ئامېرىكا قوشما شىتاتلىرى",
    "official_name:ur": "ریاست ہائے متحدہ",
    "official_name:vi": "Hợp chúng quốc Hoa Kỳ;Hợp chúng quốc Hoa Kì;Hợp chủng quốc Hoa Kỳ;Hợp chủng quốc Hoa Kì",
    "old_name:ar": "الولايات المتحدة الأمريكية الشمالية",
    "old_name:de": "Vereinigte Staaten von Nordamerika",
    "old_name:en": "United States of North America",
    "old_name:eo": "Unuiĝintaj Ŝtatoj de Nordameriko",
    "old_name:es": "Estados Unidos de Norteamérica",
    "old_name:ko": "북아메리카합중국",
    "old_name:pl": "Stany Zjednoczone Ameryki Północnej",
    "old_name:ru": "Северо-Американские Соединённые Штаты",
    "old_name:vi": "Mỹ Lợi Kiên;Ma Ly Căn;Nhã Di Lý",
    "old_short_name:ru": "САСШ",
    "population": "331449281",
    "population:date": "2020",
    "short_name": "USA",
    "short_name:az": "ABŞ",
    "short_name:be": "ЗША",
    "short_name:bg": "САЩ",
    "short_name:cs": "Spojené státy",
    "short_name:en": "USA",
    "short_name:es": "EE.UU.",
    "short_name:fr": "É.-U.",
    "short_name:ko": "미국",
    "short_name:mo": "СУА",
    "short_name:nl": "VS",
    "short_name:pl": "USA",
    "short_name:ru": "США",
    "short_name:sr": "САД",
    "short_name:sr-Latn": "SAD",
    "short_name:tr": "ABD",
    "short_name:vi": "Mỹ",
    "short_name:zh": "美国/美國",
    "short_name:zh-Hans": "美国",
    "short_name:zh-Hant": "美國",
    "source:population": "census.gov",
    "type": "boundary",
    "wikidata": "Q30",
    "wikipedia": "en:United States"
  }
},
{
  "type": "area",
  "id": 3600175905,
  "tags": {
    "admin_level": "5",
    "alt_name": "New York City",
    "alt_name:it": "Nuova York",
    "alt_name:pt": "Cidade de Nova Iorque",
    "alt_name:vi": "Thành phố New York;Thành phố Nữu Ước;Thành phố Nữu Ước;Niu Oóc;Thành phố Niu Oóc",
    "border_type": "city",
    "boundary": "administrative",
    "gnis:feature_id": "2395220",
    "is_in:country_code": "US",
    "is_in:state": "New York",
    "is_in:state_code": "NY",
    "loc_name": "Big Apple",
    "name": "City of New York",
    "name:ar": "نيويورك",
    "name:be": "Нью-Ёрк",
    "name:be-tarask": "Нью-Ёрк",
    "name:br": "Evrog Nevez",
    "name:ca": "Nova York",
    "name:cs": "New York",
    "name:cy": "Efrog Newydd",
    "name:de": "New York",
    "name:el": "Νέα Υόρκη",
    "name:en": "New York",
    "name:eo": "Novjorko",
    "name:es": "Nueva York",
    "name:fa": "نیویورک",
    "name:fr": "New York",
    "name:gl": "Nova York",
    "name:he": "ניו יורק",
    "name:hi": "न्यूयॊर्क्",
    "name:hr": "New York",
    "name:is": "Nýja Jórvík",
    "name:it": "New York",
    "name:ja": "ニューヨーク",
    "name:jbo": ".nu,IORK.",
    "name:kn": "ನ್ಯೂಯೊರ್ಕ್",
    "name:ko": "뉴욕",
    "name:oc": "Nòva York",
    "name:pl": "Nowy Jork",
    "name:pt": "Nova Iorque",
    "name:ru": "Нью-Йорк",
    "name:te": "న్యూయొర్క్",
    "name:uk": "Нью-Йорк",
    "name:vi": "New York",
    "name:zh": "纽约/紐約",
    "name:zh-Hans": "纽约",
    "name:zh-Hant": "紐約",
    "nist:fips_code": "3608151000",
    "old_name:cs": "Nový York",
    "old_name:it": "Nuova York",
    "place": "city",
    "population": "8467513",
    "population:date": "2021-07-01",
    "ref:us:ny:swis": "650000",
    "short_name": "NYC",
    "source:name:oc": "Lo Congrès",
    "source:population": "https://www.census.gov/quickfacts/newyorkcitynewyork",
    "type": "boundary",
    "website": "https://www.nyc.gov",
    "wikidata": "Q60",
    "wikimedia_commons": "Category:New York City",
    "wikipedia": "en:New York City"
  }
},
{
  "type": "area",
  "id": 3600369518,
  "tags": {
    "admin_level": "6",
    "alt_name": "Brooklyn",
    "alt_name:ru": "Бруклин",
    "border_type": "county",
    "boundary": "administrative",
    "gnis:feature_id": "974122",
    "name": "Kings County",
    "name:kaa": "Kings okrugı",
    "name:ru": "округ Кингс",
    "name:sr": "Округ Кингс",
    "name:sr-Latn": "Okrug Kings",
    "nist:fips_code": "36047",
    "population": "2736074",
    "ref:us:ny:swis": "610000",
    "source:population": "https://gis.ny.gov/civil-boundaries/ 2020",
    "type": "boundary",
    "wikidata": "Q11980692"
  }
},
{
  "type": "area",
  "id": 3603955977,
  "tags": {
    "ele": "29",
    "gnis:county_id": "103",
    "gnis:created": "01/23/1980",
    "gnis:edited": "06/11/2008",
    "gnis:feature_id": "977426",
    "gnis:state_id": "36",
    "name": "Long Island",
    "name:en": "Long Island",
    "name:ru": "остров Лонг-Айленд",
    "place": "island",
    "population": "7804968",
    "source": "NYS GIS Clearinghouse",
    "type": "multipolygon",
    "wikidata": "Q18438",
    "wikipedia": "en:Long Island"
  }
},
{
  "type": "area",
  "id": 3606496417,
  "tags": {
    "boundary": "timezone",
    "name": "America/New_York Timezone",
    "name:de": "Zeitzone Amerika/New York",
    "name:es": "Zona Horaria de América/Nueva York",
    "timezone": "America/New_York",
    "type": "boundary",
    "wikidata": "Q28146035"
  }
},
{
  "type": "area",
  "id": 3609331155,
  "tags": {
    "alt_name": "United States Mainland;Conterminus United States;The Lower 48",
    "alt_name:en": "United States Mainland;Conterminus United States;The Lower 48",
    "alt_name:es": "Estados Unidos continentales",
    "alt_name:fr": "États-Unis continentaux",
    "alt_name:vi": "Hoa Kì lục địa",
    "boundary": "region",
    "name": "Contiguous United States",
    "name:en": "Contiguous United States",
    "name:es": "Estados Unidos contiguos",
    "name:fr": "États-Unis contigus",
    "name:vi": "Hoa Kỳ lục địa",
    "note": "The exact definition of CONUS is unclear, but for now let's use \"the administrative territory of the U.S. states, excluding Alaska and Hawaii (i.e. Lower 48) plus D.C.\"",
    "place": "region",
    "short_name": "CONUS",
    "short_name:en": "CONUS",
    "type": "boundary",
    "wikidata": "Q578170",
    "wikipedia": "en:Contiguous United States"
  }
},
{
  "type": "area",
  "id": 3609691750,
  "tags": {
    "admin_level": "7",
    "boundary": "administrative",
    "name": "Brooklyn",
    "name:en": "Brooklyn",
    "name:he": "ברוקלין",
    "name:hr": "Brooklyn",
    "name:kaa": "Bruklin",
    "name:ru": "Бруклин",
    "name:sr": "Бруклин",
    "name:sr-Latn": "Bruklin",
    "name:zh-Hans": "布鲁克林区",
    "name:zh-Hant": "布魯克林區",
    "nist:fips_code": "36047",
    "place": "suburb",
    "population": "2736074",
    "ref:us:ny:swis": "610000",
    "source:population": "https://gis.ny.gov/civil-boundaries/ 2020",
    "type": "boundary",
    "wikidata": "Q18419",
    "wikipedia": "en:Brooklyn"
  }
},
{
  "type": "area",
  "id": 3613514841,
  "tags": {
    "boundary": "timezone",
    "name": "UTC-05:00 standard time",
    "type": "boundary",
    "wikidata": "Q5390"
  }
}

  ]
}

**Comment by louis-e** [comment]
Did you run arnis.py like mentioned in https://github.com/louis-e/arnis/issues/20#issuecomment-1774189235?

**Comment by PopsEj** [comment]
> Did you run arnis.py like mentioned in [#20 (comment)](https://github.com/louis-e/arnis/issues/20#issuecomment-1774189235)?

yes

**Comment by louis-e** [comment]
And does it work now?

**Comment by PopsEj** [comment]
> And does it work now?

no it tells me no data available even tho I created data for New York I'm new to overpass so I dont really know how it works

**Comment by PopsEj** [comment]
> And does it work now?

so can you do a tutorial on YouTube

**Comment by PopsEj** [comment]
> And does it work now?

I dont really know how to fetch data from there

**Comment by PopsEj** [comment]
Fetching data...
Chosen server: https://z.overpass-api.de/api/interpreter
Error! No data available
tadsandy7@elijahs-MBP desktop %

**Comment by louis-e** [comment]
Sorry for the late response, I'm really busy currently.
Will look into this as soon as I can - it's definitely one of the top priority todo's currently!

**Comment by louis-e** [comment]
Small update from my side: seems like the parameters given for NYC aren't the exact ones matching with the ones from OSM. I'm trying to find the exact ones right now, I will update you here as soon as I find them. This is by the way a general problem we have with OSM and we're already looking into possible solutions for that. Thanks for your patience!

**Comment by louis-e** [comment]
Alright, I just coded a fix for your case.
Please replace the `query1 =` line (17-39) in https://github.com/louis-e/arnis/blob/main/src/getData.py in your code with the following:
```
query1 = f"""
    [out:json];
    area[name="{city}"]->.city;
    area[name="{country}"]->.country;
    area[name="Manhattan"]->.manhattan;
    (
	way(area.country)(area.city)(area.manhattan)[building];
	way(area.country)(area.city)(area.manhattan)[highway];
	way(area.country)(area.city)(area.manhattan)[landuse];
	way(area.country)(area.city)(area.manhattan)[natural];
	way(area.country)(area.city)(area.manhattan)[leisure];
	way(area.country)(area.city)(area.manhattan)[waterway]["waterway"!="fairway"];
	way(area.country)(area.city)(area.manhattan)[amenity];
	way(area.country)(area.city)(area.manhattan)[bridge];
	way(area.country)(area.city)(area.manhattan)[railway];
	way(area.country)(area.city)(area.manhattan)[barrier];
    );
    (._;>;);
    out;
    """
```

Then try running it again with the same command. Keep in mind that NYC might take a lot of time to generate! Thanks a lot for your patience :)

**Comment by louis-e** [comment]
Another addition; my computer isn't able to run the algorithm for New York City. You might encounter the same error, unless you have more than 135 GiB of ram memory. ;)
`numpy.core._exceptions._ArrayMemoryError: Unable to allocate 135. GiB for an array with shape (7404865, 19541, 1) and data type uint8`

A solution for this would be to split up the processData array into several smaller ones, but this still has to be implemented into the algorithm and might require some intensive work (https://github.com/louis-e/arnis#memo-todo).

**Comment by PopsEj** [comment]
ok that is fine but can you do Bayonne and jersey city instead
with a little bit of ocean selected
