### ISSUE TITLE
Empty world

### ISSUE THREAD

**Issue by MKwareContributions** [louis-e/arnis#24]
Arnis finishes up successfully, but I don't see the city built in the world.
Is it being generated at some specific coordinates? Or Arnis supports only specific game version?

**Comment by PopsEj** [comment]
how did you even do overpass to create the world for me it says no data available

**Comment by louis-e** [comment]
Hi there, thanks for reporting that issue!
Sorry for the late response, I'm really busy currently. But I'll look into this soon!

**Comment by louis-e** [comment]
Hi there! Normally the world should be built nearby the spawn location. Did you maybe use a world in which you've already travelled away from the spawn location?
