### ISSUE TITLE
No Data Available.

### ISSUE THREAD

**Issue by PopsEj** [louis-e/arnis#25]
Every time it selects a server it says 

Fetching data...
Chosen server: https://overpass-api.de/api/interpreter
Error! No data available

and here's an image of the data I have 
<img width="1422" alt="Screenshot 2023-12-17 at 7 54 25 AM" src="https://github.com/louis-e/arnis/assets/143969391/639f6c24-1d16-471b-a9bc-b4fc8933d83e">

**Comment by louis-e** [comment]
That sounds like the city name input parameters are not correct, how do you run the program?

**Comment by PopsEj** [comment]
> That sounds like the city name input parameters are not correct, how do you run the program?

python arnis.py --debug --city “bayonne” --state “new-jersey” --country “united-states” --path /Users/tadsandy7/Downloads/bayonneandstatenisllandattept

**Comment by PopsEj** [comment]
> That sounds like the city name input parameters are not correct, how do you run the program?

I dont know Bayonne in open street map form

**Comment by PopsEj** [comment]
> That sounds like the city name input parameters are not correct, how do you run the program?
so do you know Bayonne in this form? new jersey?

**Comment by louis-e** [comment]
Hi there, better late then never! I just merged an awesome PR and a refactoring which should address this issue. Try to use the bbox method described in the README instead of the city/state/country input.
