### ISSUE TITLE
Weird map generation

### ISSUE THREAD

**Issue by saftey1122** [louis-e/arnis#26]
I've been toying with the tool for a while now and I've noticed that there are still some problems with map generation.
I'm not entirely sure where the problem lies as I haven't gone through to understand the code but after implementing a way to read osm json files as the data instead so I could manage the query better on overpass api I found that even with the exact data I still get weird map generations like this.

![image](https://github.com/louis-e/arnis/assets/21113793/53c64961-0b56-4be4-b796-88d5f0efacae)
![image](https://github.com/louis-e/arnis/assets/21113793/a2efed14-fa0b-4907-a4fe-89f26f43a3ea)

**Comment by saftey1122** [comment]
I do hope that this tool is still being maintained because it's really cool and I'd hope to contribute to it.

**Comment by saftey1122** [comment]
Sorry for long response, I forked the repo with all the changes I made on there (including some optimisations).

I mainly did all my generation on cities within the UK and tried a lot of different map data approaches to achieve these results.

I also used a Minecraft mod for a map view and the debug image file to see if the world would generate weird or not as a quicker approach.

If you could walk me through the logic of how you translate the map data provided into minecraft coordinates and such I can see what else I can cook up to help the script!

**Comment by louis-e** [comment]
Hi there, better late then never! I just merged an awesome PR and a refactoring which should address this issue.
