### ISSUE TITLE
when I try running the command it kills the session

### ISSUE THREAD

**Issue by PopsEj** [louis-e/arnis#28]
Fetching data...
Chosen server: https://lz4.overpass-api.de/api/interpreter
Parsing data...
zsh: killed python3 arnis.py --city "The Bronx" --state "New York" --country --path

I fixed the no data error but now I got this even when I try on colab its says ^C and interrupt

**Comment by daniil2327** [comment]
try my fork with bbox:)
http://bboxfinder.com/

**Comment by louis-e** [comment]
Fix by @daniil2327 is merged, will close this issue now
