### ISSUE TITLE
Pyinstaller binaries and releases

### ISSUE THREAD

**Issue by amir16yp** [louis-e/arnis#33]
I would consider creating single-file binaries with pyinstaller, and have github actions automatically publish nightly builds with each commit pushed to main. this would make it so users could just download a single binary for their system, whether its windows, linux or even intel macs, without tinkering with installing python and the dependencies which can be troublesome for a lot of non-programmers.

**Comment by daniil2327** [comment]
I want to try to write a GUI for this project, and after that your idea can be done

**Comment by amir16yp** [comment]
> I want to try to write a GUI for this project, and after that your idea can be done

a gui shouldnt be too hard. just wrapping the command around qt or tk.
on my fork i am testing pyinstaller build workflows for the CLI.

**Comment by daniil2327** [comment]
I will write gui in tk because it is not complicated

**Comment by louis-e** [comment]
Gonna mention the binary release workflow PR just for reference here: https://github.com/louis-e/arnis/pull/35
I'll keep this issue open for the GUI implementation.
