### ISSUE TITLE
Failed to download data. Status code: 400

### ISSUE THREAD

**Issue by Tannermanner2008** [louis-e/arnis#34]
![failed](https://github.com/user-attachments/assets/8b684f2f-a675-429e-a5e3-28c4a99d8280)

I downloaded the dependencies and inputted the bbox lat and lng values and it causes an error and usually i'd just write this off as the api used not working. however, the version before the lat and lng requirement, when you still had to use city, state and country, works fine ONLY using the example you gave for germany.

is there any reason for it not working?

**Comment by Tannermanner2008** [comment]
> This server can't process your request (overloaded), please try again

i've tried multiple times yesterday and today with no working result though. i've been trying again

**Comment by daniil2327** [comment]
can you send me the code with which you run the program?

**Comment by Tannermanner2008** [comment]
D:\arnis-main\arnis-main>py -3.12 arnis.py --bbox="-788.411865,45.067502,-784.401855,47.998151" --path="C:/Users/[my username]/AppData/Roaming/.minecraft/saves/irl test"

**Comment by daniil2327** [comment]
your bbox is incorrect because it goes beyond the possible boundaries

**Comment by Tannermanner2008** [comment]
alrght it's working now, thanks so much for the quick replies!
