### ISSUE TITLE
when I put the bbox coords it says no data available

### ISSUE THREAD

**Issue by PopsEj** [louis-e/arnis#43]
Fetching data...
Error! No data available

**Comment by louis-e** [comment]
Hi there! Could you please provide the --bbox parameter you used so we can reproduce the issue?

**Comment by PopsEj** [comment]
> Hi there! Could you please provide the --bbox parameter you used so we can reproduce the issue?

python3 arnis.py --bbox="-74.277191,40.489782,-73.782806,40.928040” --path="/Users/tadsandy7/Downloads/FlatWorld”
