### ISSUE TITLE
[FEATURE] Scale feature 

### ISSUE THREAD

**Issue by huiiksde** [louis-e/arnis#49]
Ability to scale the generated map. For example: scale=“1.7” or scale="0.6”

**Comment by louis-e** [comment]
Hi there, thanks for the feature request!
Sounds like a good idea, I will add this to an upcoming release. In the meantime you can tweak the SCALE_FACTOR variable in processData.py (line 13) to achieve this.

**Comment by huiiksde** [comment]
So how to change scale on version 2.1.0?

**Comment by faithsapling** [comment]
Can we please make it so the scale can go as low as 0.1? I feel like it's a bit limiting that I can only scale down to 0.5, but it seems there's way more options for scaling way higher.
