### ISSUE TITLE
[BUG] Chunk file at [<X>, <Y>] is in the wrong location; relocating. (Expected [<X>, <Y>], got [<X-96>, <Y-96>])

### ISSUE THREAD

**Issue by skullydazed** [louis-e/arnis#53]
**Describe the bug**
Immediately after generating the world I get a lot of "Failed to load chunk" messages. The log file gives me the details from the title.

**Used bbox parameter**
```
python3 arnis.py --bbox="-122.078576,37.039181,-122.051110,37.056033" --path ~/.minecraft/saves/Felton
```

**Screenshots**
Will attach log files

**Additional context**
Using Java Minecraft 1.21.1. This is in a brand-new world generated with these parameters (Classic Flat):

```
minecraft:bedrock,2*minecraft:dirt,minecraft:grass_block;minecraft:plains
```

**Comment by skullydazed** [comment]
[chunk-Felton-2024-09-14_13.29.56-server.txt](https://github.com/user-attachments/files/17003734/chunk-Felton-2024-09-14_13.29.56-server.txt)

**Comment by skullydazed** [comment]
I should note that the world otherwise loads and plays correctly, but there's a lot of logging and the "Failed to load chunk" message on screen basically all the time.

**Comment by louis-e** [comment]
Hi there!
Thanks for the report. I think this is a similar issue to https://github.com/louis-e/arnis/issues/38. I'm aware of this issue and I'm trying to resolve this with a currently ongoing port of the entire project to the Rust language. I think this isn't a major problem right now so my priority on this is not as high as on other things to fix, but I'll look into this!

**Comment by skullydazed** [comment]
Thanks for the fast response here! Glad to hear you're already aware and have a plan. Do you want to leave this open for tracking purposes, or close it?
