### ISSUE TITLE
HTTP error 404: Not Found

### ISSUE THREAD

**Issue by UnknownSuperficialNight** [louis-e/arnis#60]
**Describe the bug**
Tried to run the program but it can't find the remote Cargo.toml

**Used bbox parameter**
`--bbox="-0.634843,51.065431,0.722043,51.767642"`

**Screenshots**
![image](https://github.com/user-attachments/assets/d91be70d-9fdd-4d1c-8bc0-c211fbb9f3b8)

**Additional context**
Compiled myself using `cargo build --release`

**Comment by louis-e** [comment]
Hi there! Thanks for reporting this issue, this is fixed now. I accidentally left in an url to the old development branch. So should be working now!

Also, you migght want to start with generating smaller areas, since your bbox size might reach the limits of the OpenStreetMaps API. :D
