### ISSUE TITLE
[BUG]  Buildings generated over roads

### ISSUE THREAD

**Issue by FractalFir** [louis-e/arnis#65]
**Describe the bug**
Arnis generates buildings over roads, which seems incorrect.

**Used bbox parameter**
14.538603,53.447248,14.553018,53.467511
**Screenshots**

![2024-09-21_21 23 53](https://github.com/user-attachments/assets/b9c3b1dd-cf42-4866-b749-238fc873a930)
![2024-09-21_21 26 09](https://github.com/user-attachments/assets/cd5c9981-5718-4b8f-b056-8ed446963640)
![2024-09-21_21 28 57](https://github.com/user-attachments/assets/ed92a4a0-8068-4414-9072-721703e77c8d)

![2024-09-21_21 28 52](https://github.com/user-attachments/assets/ff623d26-7efa-43a3-b35c-50d3f53a0a81)
![2024-09-21_21 29 22](https://github.com/user-attachments/assets/feb26656-b742-4ccc-93c5-bf3fb86c5700)

**Comment by louis-e** [comment]
Hi there! Thanks for the report, I just fixed this in https://github.com/louis-e/arnis/commit/96ad9ebd34da2b8ac27a8db811ffc6d57eac66c9. :)
