### ISSUE TITLE
[DISCUSSION] There should be a final release of the python legacy version

### ISSUE THREAD

**Issue by amir16yp** [louis-e/arnis#68]
I think there should be a 1.1 release, because there were a few QoL changes before the rust release and after 1.0 release.

**Comment by daniil2327** [comment]
I think we need to do almost the entire to-do list and make a final release

**Comment by amir16yp** [comment]
> I think we need to do almost the entire to-do list and make a final release

the python release is done for, development will pretty much continue on the rust version

**Comment by louis-e** [comment]
Thanks for the feedback, any specific changes you're looking for which aren't fixed or on the implementation todo list for the Rust port? I'm currently working in parallel on several major changes, including a memory efficient chunk processing which I want to release asap. I think we've covered pretty much everything from the Python legacy version, if not even better. Thus I'd preferably want to focus completely on the Rust port, but I'm open to releasing a v1.1 if you can convince me! :)
