### ISSUE TITLE
[DISCUSSION] Help needed with placing a sign :)

### ISSUE THREAD

**Issue by vfosnar** [louis-e/arnis#70]
Hi, I'm trying to place a sign with some text on it. So far I've tried the following code, but it only results in a sign hitbox with no texture. Properties do get recognized by Minecraft. For example if I set "waterlogged" to "true" the water appears, but still no sign.

```rust
let sign: once_cell::sync::Lazy<Block> =
    once_cell::sync::Lazy::new(|| {
        Block::new(
            "minecraft",
            "oak_sign",
            Some(nbt!({
                "rotation": "5",
                "waterlogged": "false"
            })),
        )
    });
editor.set_block(&sign, x, ground_level + 1, z, None, None);
```

**Comment by louis-e** [comment]
Hi there!
I looked into this using NBTExplorer and stumbled upon this:
![image](https://github.com/user-attachments/assets/0c520349-020b-447a-8be4-353803214a6e)
For a sign to work, there must be an according entry in block_entities like in the image above.

However, when generating the world with Arnis, the block_entities field isn't taken into account. We'd need to implement a logic for this too:
![image](https://github.com/user-attachments/assets/855e060b-a39b-4567-a415-c33255936243)

I hope this helps. If I find some time, I can spend some work on this. :)
