### ISSUE TITLE
I can't create a world. Not enough memory.

### ISSUE THREAD

**Issue by huiiksde** [louis-e/arnis#72]
After porting to Rust, I can't create a world because creating it takes too much RAM. I get the error “memory allocation of 123920 bytes failed”. And I have 16GB of RAM

**Comment by daniil2327** [comment]
Same error #63

**Comment by louis-e** [comment]
Thanks for the report! Will be solved soon.
I already have a working memory safe version, I just need to fix some bugs in it before publishing it!
