### ISSUE TITLE
Memory allocation error

### ISSUE THREAD

**Issue by kosssst** [louis-e/arnis#8]
```
>>> python arnis.py --city "Київ" --state "Київ" --country "Україна" --path "E:/kyiv"
Fetching data...
Chosen server: https://overpass.kumi.systems/api/interpreter
Parsing data...
Traceback (most recent call last):
  File "D:\arnis\arnis.py", line 7, in <module>
    from src.main import run
  File "D:\arnis\src\main.py", line 118, in <module>
    imgarray = processData(rawdata, args)
  File "D:\arnis\src\processData.py", line 56, in processData
    img = np.zeros(
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 275. GiB for an array with shape (1181055, 250396, 1) and data type uint8
```
Hi, when I try to run this script I catch this error. Can anyone help me?

**Comment by basdvnjksnjksvnsdjknK** [comment]
obviously you need to buy more RAM

**Comment by kostyamed** [comment]
275 GB?

**Comment by kosssst** [comment]
`>>> python arnis.py --city "Київ" --state "Київ" --country "Україна" --path "D:/kyiv"
Fetching data...
Chosen server: https://z.overpass-api.de/api/interpreter
Parsing data...
Traceback (most recent call last):
  File "D:\arnis\arnis.py", line 10, in <module>
    run()
  File "D:\arnis\src\main.py", line 123, in run
    imgarray = processData(rawdata, args)
  File "D:\arnis\src\processData.py", line 150, in processData
    img = np.zeros(
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 269. GiB for an array with shape (1181164, 244972, 1) and data type uint8`

@louis-e, I checked commit history and and you pointed out that you improved RAM usage, but problem is still here.
