### ISSUE TITLE
[BUG] Using PrismLauncher, 'main panicked at  src/worldeditor.rs

### ISSUE THREAD

**Issue by RXTransit** [louis-e/arnis#86]
![Screenshot (152)](https://github.com/user-attachments/assets/52af378d-7e22-4171-9227-653ae614a7b3)

.\arnis.exe --path=C:/Users/Rex/AppData/Roaming/PrismLauncher/instances/Minecraft/.minecraft/saves/"New World" --bbox="115.744459,-32.052544,115.746626,-32.051444"

I did everything right, 

on 1.19.2

**Comment by daniil2327** [comment]
try to recreate the world or check the path, also the path to the world should be in quotes

**Comment by RXTransit** [comment]
> try to recreate the world or check the path, also the path to the world should be in quotes

Tried both things, the path was correct - same error

**Comment by faithsapling** [comment]
I'm having the same issues :(

**Comment by vyual** [comment]
same

**Comment by enderjulien** [comment]
same 💔

**Comment by louis-e** [comment]
Thanks for all the feedback & sorry for the bug, this is fixed in the newest release now! [arnis/releases](https://github.com/louis-e/arnis/releases)
